### ISSUE TITLE
Resolve file with no parents.

### ISSUE THREAD

**Issue by stevepeak** [codecov/pathmap#11]
```diff
python -c "from pathmap import resolve_by_method; resolve_by_method(['folder/file.py'])('file.py', ancestors=1)"
- >>> None
+ >>> "folder/file.py"
```

@naglalakk Can you help fix this one up?

**Comment by naglalakk** [comment]
Is it suppose to return None or folder/file.py? Currently I'm getting

```
>>> resolve_by_method(',folder/file.py,')('file.py', ancestors=1)
'folder/file.py'
```

is it suppose to return None instead?

**Comment by stevepeak** [comment]
I need to review how this issue was created again. I must be confused. Thanks @naglalakk
